name: SonarCloud Analysis (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven  # Habilita la caché de dependencias de Maven para optimizar tiempo

      - name: Compilar el proyecto
        run: mvn clean install

      - name: Ejecutar pruebas con cobertura
        run: mvn verify jacoco:report

      - name: Ejecutar análisis con SonarCloud usando Maven
        run: mvn sonar:sonar -Dsonar.projectKey=cr15v_manejador-de-tareas -Dsonar.organization=cr15v -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
