name: SonarQube Analysis (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Descargar y extraer Sonar Scanner
        run: |
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar-scanner.zip"
          Expand-Archive -Path "sonar-scanner.zip" -DestinationPath "sonar-scanner"
          echo "$PWD\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Ejecutar análisis con SonarCloud
        run: |
          sonar-scanner.bat `
            -Dsonar.organization=<cr15v> `
            -Dsonar.projectKey=<cr15v_manejador-de-tareas> `
            -Dsonar.host.url=https://sonarcloud.io `
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
